Filtering
adobe/blog pull request #28
Opened 2021-10-25 22:08 UTC by fkakatie

## Description

build filtering feature for topics pages in parallel with existing blog

## Related Issue

#3 

## Links

https://filtering--blog--adobe.hlx3.page/en/topics/creativity
https://filtering--blog--adobe.hlx3.page/en/topics/creativity?delayed=off
https://filtering--blog--adobe.hlx3.page/?delayed=off
https://filtering--blog--adobe.hlx3.page/en/publish/2021/10/15/adobe-max-bringing-creativity-heart-education?delayed=off

2021-11-02 11:15 UTC, kptdobe requested changes

2021-11-02 11:15 UTC, kptdobe commented on blocks/article-feed/article-feed.js
> +        if (filters.selectedproducts && filters.selectedindustries) {
Why not: 
```suggestion
        if (filters.selectedProducts && filters.selectedIndustries) {
```

2021-11-02 11:17 UTC, kptdobe commented
The merge of the main branch did something wrong, I had to manually restore some code changes I brought recently which are improving the speed of the article-feed (paging the data filtering instead of the elements to render). I hope I did not break it.

2021-11-03 21:01 UTC, fkakatie commented
<img width="780" alt="Screen Shot 2021-11-03 at 3 00 15 PM" src="https://user-images.githubusercontent.com/43383503/140191932-3c7dd93d-220f-4bfb-a838-c8b8c0c6c8ac.png">

Not sure where the 88 is coming from.

2021-11-04 08:08 UTC, kptdobe approved these changes

2021-11-04 08:09 UTC, merged